Change RECOVERY_ to RM_ for brevity and to work with same change in 00-set-stage.

diff --git a/recover-machine-01-get-src-directories b/recover-machine-01-get-src-directories
--- a/recover-machine-01-get-src-directories
+++ b/recover-machine-01-get-src-directories
@@ -1,40 +1,47 @@
 #!/usr/bin/bash
 
-if [[ ! -d "$RECOVERY_STAGEDIR" ]]
+[[ -z "$DEBUG" ]] || set -x # Enable debugging
+set -e # exit on error to be safe
+
+if [[ -z "$RM_STAGEDIR" && -d _stage ]]
 then
+  export RM_STAGEDIR="_stage"
+else
   echo -e "\n    Did you run recover-machine-00-set-stage?"
   exit 1
-elif [[ -r $RECOVERY_STAGEDIR/00-FUNCTIONS && \
-        -r $RECOVERY_STAGEDIR/00-LOCALENV  ]]
+fi
+
+if [[ -r $RM_STAGEDIR/00-FUNCTIONS && \
+        -r $RM_STAGEDIR/00-LOCALENV  ]]
 then
-  source $RECOVERY_STAGEDIR/00-FUNCTIONS 
-  source $RECOVERY_STAGEDIR/00-LOCALENV 
+  source $RM_STAGEDIR/00-FUNCTIONS 
+  source $RM_STAGEDIR/00-LOCALENV 
 else
   echo -e "\n    Can't find all my files:"
-  ls -l $RECOVERY_STAGEDIR/00-FUNCTIONS
-  ls -l $RECOVERY_STAGEDIR/00-LOCALENV
+  ls -l $RM_STAGEDIR/00-FUNCTIONS
+  ls -l $RM_STAGEDIR/00-LOCALENV
 fi
 
 echo -e "\n    Archive source directories on source machine"
-juju ssh "$RECOVERY_SRC_MACHINENUM" sudo tar -C /var/lib -c${V}f /tmp/src_var_lib.tar \
+juju ssh "$RM_SRC_MACHINENUM" sudo tar -C /var/lib -c${V}f /tmp/src_var_lib.tar \
                                             ./juju
-juju ssh "$RECOVERY_SRC_MACHINENUM" sudo tar -C /etc/systemd/system -c${V}f /tmp/src_etc_systemd_system.tar \
-                                            ./jujud-${RECOVERY_SRC_MACHINE}-exec-start.sh \
-                                            ./jujud-${RECOVERY_SRC_MACHINE}.service
-juju ssh "$RECOVERY_SRC_MACHINENUM" ls -l /tmp/src_*.tar
+juju ssh "$RM_SRC_MACHINENUM" sudo tar -C /etc/systemd/system -c${V}f /tmp/src_etc_systemd_system.tar \
+                                            ./jujud-${RM_SRC_MACHINE}-exec-start.sh \
+                                            ./jujud-${RM_SRC_MACHINE}.service
+juju ssh "$RM_SRC_MACHINENUM" ls -l /tmp/src_*.tar
 
 echo -e "\n    Retrieve source directory archives from source machine"
-juju scp "$RECOVERY_SRC_MACHINENUM":/tmp/src_var_lib.tar            $RECOVERY_STAGEDIR/01_SRC_var_lib.tar
-juju scp "$RECOVERY_SRC_MACHINENUM":/tmp/src_etc_systemd_system.tar $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system.tar
-ls -l $RECOVERY_STAGEDIR/01_SRC_*.tar
+juju scp "$RM_SRC_MACHINENUM":/tmp/src_var_lib.tar            $RM_STAGEDIR/01_SRC_var_lib.tar
+juju scp "$RM_SRC_MACHINENUM":/tmp/src_etc_systemd_system.tar $RM_STAGEDIR/01_SRC_etc_systemd_system.tar
+ls -l $RM_STAGEDIR/01_SRC_*.tar
 
-recover_mkdir $RECOVERY_STAGEDIR/01_SRC_var_lib
-recover_mkdir $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system
+recover_mkdir $RM_STAGEDIR/01_SRC_var_lib
+recover_mkdir $RM_STAGEDIR/01_SRC_etc_systemd_system
 
 echo -e "\n    Extract source directories from archives"
-sudo tar -C      $RECOVERY_STAGEDIR/01_SRC_var_lib            -x${V}f $RECOVERY_STAGEDIR/01_SRC_var_lib.tar
-sudo tar -C      $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system -x${V}f $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system.tar
-echo "$RECOVERY_STAGEDIR/01_SRC_var_lib:"
-ls -l $RECOVERY_STAGEDIR/01_SRC_var_lib
-echo "$RECOVERY_STAGEDIR/01_SRC_etc_systemd_system:"
-ls -l $RECOVERY_STAGEDIR/01_SRC_etc_systemd_system
+sudo tar -C      $RM_STAGEDIR/01_SRC_var_lib            -x${V}f $RM_STAGEDIR/01_SRC_var_lib.tar
+sudo tar -C      $RM_STAGEDIR/01_SRC_etc_systemd_system -x${V}f $RM_STAGEDIR/01_SRC_etc_systemd_system.tar
+echo "$RM_STAGEDIR/01_SRC_var_lib:"
+ls -l $RM_STAGEDIR/01_SRC_var_lib
+echo "$RM_STAGEDIR/01_SRC_etc_systemd_system:"
+ls -l $RM_STAGEDIR/01_SRC_etc_systemd_system
