Add work new in output description of new target directories.

diff --git a/recover-machine-03-stage-and-edit-tgt-target-directories b/recover-machine-03-stage-and-edit-tgt-target-directories
--- a/recover-machine-03-stage-and-edit-tgt-target-directories
+++ b/recover-machine-03-stage-and-edit-tgt-target-directories
@@ -40,7 +40,7 @@ fi
 recover_mkdir $RM_STAGEDIR/03_TGT_NEW_var_lib
 recover_mkdir $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system
 
-echo "==== Extract source directory archives into target directories"
+echo "==== Extract source directory archives into new target directories"
 sudo tar -C $RM_STAGEDIR/03_TGT_NEW_var_lib            -x${V}f $RM_STAGEDIR/01_SRC_var_lib.tar
 sudo tar -C $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system -x${V}f $RM_STAGEDIR/01_SRC_etc_systemd_system.tar
 echo $RM_STAGEDIR/03_TGT_NEW_var_lib:
@@ -48,7 +48,7 @@ ls -l  $RM_STAGEDIR/03_TGT_NEW_var_lib
 echo $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system:
 ls -l  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system
 
-echo "==== Edit target files"
+echo "==== Edit new target files"
 sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/unit*
 sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/meter-status.yaml
 sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/locks/*
@@ -58,13 +58,17 @@ sudo rm -rf $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/nonce.txt
 sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_SRC_MACHINE} $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_TGT_MACHINE}
 sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RM_SRC_MACHINE}  $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/tools/${RM_TGT_MACHINE}
 sudo sudo sed -i "s/${RM_SRC_MACHINE}/${RM_TGT_MACHINE}/g" $RM_STAGEDIR/03_TGT_NEW_var_lib/juju/agents/${RM_TGT_MACHINE}/agent.conf
-sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_var_lib $RM_STAGEDIR/03_TGT_NEW_var_lib
 sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_SRC_MACHINE}-exec-start.sh $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGT_MACHINE}-exec-start.sh
 sudo mv -f  $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_SRC_MACHINE}.service       $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGT_MACHINE}.service
 sudo sudo sed -i "s/${RM_SRC_MACHINE}/${RM_TGT_MACHINE}/g" $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system/jujud-${RM_TGT_MACHINE}*
-sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_var_lib $RM_STAGEDIR/03_TGT_NEW_var_lib
 
-echo "==== Archive target directories"
+echo "==== Diff of directories"
+set +e # Temporarily don't exit on error because we expect diff to find differences
+sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_var_lib $RM_STAGEDIR/03_TGT_NEW_var_lib
+sudo diff --recursive --unified --no-dereference $RM_STAGEDIR/01_SRC_etc_systemd_system $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system
+set -e # Exit on error again
+
+echo "==== Archive new target directories"
 sudo tar -C $RM_STAGEDIR/03_TGT_NEW_var_lib            -c${V}f $RM_STAGEDIR/03_TGT_NEW_var_lib.tar            ./
 sudo tar -C $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system -c${V}f $RM_STAGEDIR/03_TGT_NEW_etc_systemd_system.tar ./
 ls -l  $RM_STAGEDIR/03_TGT_NEW_var_lib.tar
